repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/ambv/black
    rev: stable 
    hooks:
      - id: black
        verbose: true
        args: [
          --line-length=88, 
          --target-version=py37
        ]
        exclude: ^(\.git|\.venv|venv)/
        name: Reformat with black

  - repo: local
    hooks:
      - id: flake8
        name: Lint with flake8
        entry: flake8
        additional_dependencies:
          - flake8==3.7.7
          - pep8-naming==0.8.2
          - flake8-bugbear==19.3.0
          - flake8-docstrings==1.3.0
          - flake8-import-order==0.18.1
          - flake8-mypy==17.8.0
        types: [python]
        language: python

default_language_version:
  python: python3.7
